### ISSUE TITLE
ffmpeg's output allow multiple -map arguments

### ISSUE THREAD

**Issue by lucemia** [lucemia/typed-ffmpeg#138]

**Comment by lucemia** [comment]
> This option may be specified multiple times, each adding more streams to the output file. Any given input stream may also be mapped any number of times as a source for different output streams, e.g. in order to use different encoding options and/or filters. The streams are created in the output in the same order in which the -map options are given on the commandline.

**Comment by lucemia** [comment]
```
ffmpeg.input('in.mp4').output(
...
map = [
    "[v1out] -c:v:0 libx264 -b:v:0 1900k -bufsize 3800k",
    "[v2out] -c:v:1 libx264 -b:v:0 900k -bufsize 1800k"
  ]
)
```

https://stackoverflow.com/questions/69218400/how-to-use-multiple-map-values-in-ffmpeg-python

**Comment by lucemia** [comment]
確認一下 -b, -c, -bufsize 的特性

**Comment by lucemia** [comment]
- libavcodec/options_table.h 
- 這些應該是 encoder 專門的變數
https://ffmpeg.org/ffmpeg-codecs.html

**Comment by lucemia** [comment]
this is the complete document
https://ffmpeg.org/ffmpeg-all.html#pad-1

**Comment by lucemia** [comment]
https://news.ycombinator.com/item?id=33383023

**Comment by mateusz-krainski-revoize** [comment]
I don't think this is properly handled. My case is e.g.

```
ffmpeg -y -i input.mp4 -i enhanced.wav -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac output.mp4
```

and I was not able to get a satisfactory result. 

Explicitly setting something like 

```
video_stream = ffmpeg.input(input_video_file_path).video
audio_stream = ffmpeg.input(input_audio_file_path).audio

ffmpeg.output(
    video_stream,
    audio_stream,
    filename=output_video_file_path,
    vcodec='copy',
    acodec='aac',
    shortest=True
).overwrite_output().run()
```

Produced a result like

```sh
ffmpeg -y -i /tmp/tmponxx0g90.mov -i /tmp/tmp_e49gil5.wav -vcodec copy -acodec aac /tmp/tmp1f3ap3fe.mov
```

where it looks like the selectors for audio and video are ignored. Using the original `ffmpeg-python`, this is possible like

```py
video = ffmpeg.input(input_video_path)['v']
```

(https://github.com/kkroening/ffmpeg-python/issues/420) but with `typed-ffmpeg` those selectors don't work.

**Comment by lucemia** [comment]
> I don't think this is properly handled. My case is e.g.
> 
> ```
> ffmpeg -y -i input.mp4 -i enhanced.wav -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac output.mp4
> ```
> 
> and I was not able to get a satisfactory result.
> 
> Explicitly setting something like
> 
> ```
> video_stream = ffmpeg.input(input_video_file_path).video
> audio_stream = ffmpeg.input(input_audio_file_path).audio
> 
> ffmpeg.output(
>     video_stream,
>     audio_stream,
>     filename=output_video_file_path,
>     vcodec='copy',
>     acodec='aac',
>     shortest=True
> ).overwrite_output().run()
> ```
> 
> Produced a result like `ffmpeg -y -i /tmp/tmponxx0g90.mov -i /tmp/tmp_e49gil5.wav -vcodec copy -acodec aac /tmp/tmp1f3ap3fe.mov`, where it looks like the selectors for audio and video are ignored. Using the original `ffmpeg-python`, this is possible like `video = ffmpeg.input(input_video_path)['v']` ([kkroening/ffmpeg-python#420](https://github.com/kkroening/ffmpeg-python/issues/420)) but with `typed-ffmpeg` those selectors don't work.

Yes, I can confirm this case — it looks like the stream selectors are being ignored when there’s only one output. I’ll take a closer look and aim to resolve it in the coming days. Thanks for flagging it!

**Comment by lucemia** [comment]
Hi @mateusz-krainski-revoize,

I’ve released version 2.7.0, which resolves this issue.

With the same input:
```
video_stream = ffmpeg.input(input_video_file_path).video
audio_stream = ffmpeg.input(input_audio_file_path).audio

ffmpeg.output(
    video_stream,
    audio_stream,
    filename=output_video_file_path,
    vcodec='copy',
    acodec='aac',
    shortest=True
).overwrite_output().run()
```
It will now correctly generate the following command:
```
[
  "ffmpeg",
  "-y",
  "-i",
  "input_video.mp4",
  "-i",
  "input_audio.mp3",
  "-map",
  "0:v",
  "-map",
  "1:a",
  "-shortest",
  "-vcodec",
  "copy",
  "-acodec",
  "aac",
  "output_video.mp4"
]
```
Let me know if you have any questions!

**Comment by mateusz-krainski-revoize** [comment]
It looks like the issue I've mentioned here was resolved, thank you. However, it looks like this change is not backwards compatible with other functionalities. 

We are actually using two ffmpeg commands - 1) to separate the audio from a video file (this used to work in 2.6.4 but doesn't in 2.7.2, snippet below) and 2) to replace an audio track in a video file (this was mentioned above, this now works).

This is the snippet for 1)

```py
(
    ffmpeg
    .input(original_source_file_path)
    .output(filename=new_source_file_path, acodec='pcm_s16le')
    .overwrite_output()
    .run(capture_stdout=True, capture_stderr=True)
)
```

this used to work as expected in 2.6.4, but doesn't work in 2.7.2 after the latest changes. It produces an error:

```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/Users/mateusz/Library/Caches/pypoetry/virtualenvs/revoize-scripts-vz4hxuRb-py3.11/lib/python3.11/site-packages/ffmpeg/dag/global_runnable/runnable.py", line 280, in run
    raise FFMpegExecuteError(
ffmpeg.exceptions.FFMpegExecuteError: ffmpeg -y -i samples/hi-from-revoize.mov -map 0 -acodec pcm_s16le samples/hi-from-revoize-audio.wav error (see stderr output for detail) b"ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n  built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n  libavutil      59. 39.100 / 59. 39.100\n  libavcodec     61. 19.101 / 61. 19.101\n  libavformat    61.  7.100 / 61.  7.100\n  libavdevice    61.  3.100 / 61.  3.100\n  libavfilter    10.  4.100 / 10.  4.100\n  libswscale      8.  3.100 /  8.  3.100\n  libswresample   5.  3.100 /  5.  3.100\n  libpostproc    58.  3.100 / 58.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'samples/hi-from-revoize.mov':\n  Metadata:\n    major_brand     : qt  \n    minor_version   : 0\n    compatible_brands: qt  \n    creation_time   : 2024-10-17T17:43:19.000000Z\n    com.apple.quicktime.model: iPhone 15 Pro\n    com.apple.quicktime.make: Apple\n    com.apple.quicktime.location.ISO6709: +45.4169-75.6968+082.874/\n  Duration: 00:00:17.76, start: 0.000000, bitrate: 48696 kb/s\n  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, smpte170m/bt709/bt709), 3840x2160, 48562 kb/s, 59.96 fps, 59.94 tbr, 600 tbn (default)\n      Metadata:\n        creation_time   : 2024-10-17T17:43:19.000000Z\n        handler_name    : Core Media Video\n        vendor_id       : [0][0][0][0]\n        encoder         : HEVC\n      Side data:\n        displaymatrix: rotation of -90.00 degrees\n  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 123 kb/s (default)\n      Metadata:\n        creation_time   : 2024-10-17T17:43:19.000000Z\n        handler_name    : Core Media Audio\n        vendor_id       : [0][0][0][0]\n[vost#0:0 @ 0x11d80e550] Automatic encoder selection failed Default encoder for format wav (codec none) is probably disabled. Please choose an encoder manually.\n[vost#0:0 @ 0x11d80e550] Error selecting an encoder\nError opening output file samples/hi-from-revoize-audio.wav.\nError opening output files: Encoder not found\n"
```

the same error, formatted for readability:

```
ffmpeg -y -i samples/hi-from-revoize.mov -map 0 -acodec pcm_s16le samples/hi-from-revoize-audio.wav error (see stderr output for detail)
ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.6)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'samples/hi-from-revoize.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2024-10-17T17:43:19.000000Z
    com.apple.quicktime.model: iPhone 15 Pro
    com.apple.quicktime.make: Apple
    com.apple.quicktime.location.ISO6709: +45.4169-75.6968+082.874/
  Duration: 00:00:17.76, start: 0.000000, bitrate: 48696 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, smpte170m/bt709/bt709), 3840x2160, 48562 kb/s, 59.96 fps, 59.94 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-10-17T17:43:19.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 123 kb/s (default)
      Metadata:
        creation_time   : 2024-10-17T17:43:19.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
[vost#0:0 @ 0x11d80e550] Automatic encoder selection failed Default encoder for format wav (codec none) is probably disabled. Please choose an encoder manually.
[vost#0:0 @ 0x11d80e550] Error selecting an encoder
Error opening output file samples/hi-from-revoize-audio.wav.
Error opening output files: Encoder not found
```

It looks like in 2.7.2 this command is compiled as

```sh
ffmpeg -y -i samples/hi-from-revoize.mov -map 0 -acodec pcm_s16le samples/hi-from-revoize-audio.wav
```

whereas in 2.6.4 it was compiled as 

```sh
ffmpeg -y -i samples/hi-from-revoize.mov -acodec pcm_s16le samples/hi-from-revoize-audio.wav
```

which looks like a breaking change - it used to work and now it doesn't work.

**Comment by lucemia** [comment]
Thanks for flagging this — this change isn’t backwards-compatible.

In 2.7.2, I added an explicit -map to avoid relying on FFmpeg’s default stream selection (which was causing the old issues), but I didn’t realize it would break cases like this.

The problem is that `-map 0` tells FFmpeg to include all streams — video, audio, subtitles, everything. But .wav files can only handle audio, so FFmpeg tries to include the video stream, fails to encode it into a .wav, and crashes.

I am thinking what is the best way to solve the issue.
To fix it now, you can target just the audio stream like this:

```
(
    ffmpeg
    .input(original_source_file_path).audio   # specific audio stream
    .output(filename=new_source_file_path, acodec='pcm_s16le')
    .overwrite_output()
    .compile_line()
)
```

That should generate something like:

`ffmpeg -y -i input.mp4 -map 0:a -acodec pcm_s16le output.wav`

I tested this locally and it seems to work — let me know if that does the trick for you too!

**Comment by mateusz-krainski-revoize** [comment]
Thanks for being active on this thread. I can confirm that your suggested workaround has resolved our issues and now we can use `typed-ffmpeg` for both cases. Thank you 🙏 

I would still recommend releasing a version where 

```py
(
    ffmpeg
    .input(original_source_file_path)
    .output(filename=new_source_file_path, acodec='pcm_s16le')
    .overwrite_output()
    .compile_line()
)
```

and 

```py
(
    ffmpeg
    .input(original_source_file_path).audio
    .output(filename=new_source_file_path, acodec='pcm_s16le')
    .overwrite_output()
    .compile_line()
)
```

both produce expected results for the reasons of intuitive use and backwards compatibility.

This is however up to you -- I consider my issue to be resolved. Thanks again!

**Comment by lucemia** [comment]
✅ Auto-add -map in these scenarios:

1. Multiple inputs
	•	If user adds more than one input file (e.g., video.mp4 and audio.mp3)
	•	You should explicitly map video and audio to avoid unpredictable behavior.
Example:

`-map 0:v -map 1:a`



2. User wants specific tracks
	•	If the user selects a specific audio language, subtitle, or stream index.
	•	You need -map to extract that particular stream.

3. User wants to copy streams (-c copy)
	•	FFmpeg won’t transcode, so it needs to know exactly which streams to copy.
	•	Always add -map when using -c copy.

4. Combining media (muxing)
	•	E.g., overlaying external audio on video.
	•	Mapping is necessary to ensure the right streams get merged.

5. User excludes certain streams
	•	If they say “no subtitles” or “just video, no audio,” you need -map to enforce it.

⸻

🚫 Skip -map when:

1. Single input file
	•	User does not specify any preferences.
	•	Let FFmpeg’s default selection pick first video/audio/subtitle.

2. Transcoding with defaults
	•	E.g., just compressing a file without altering streams:

ffmpeg -i input.mp4 -c:v libx264 output.mp4



⸻

🤖 Builder Rule of Thumb

Here’s a simple logic for your builder:
```
if len(inputs) > 1 or stream_selection_explicit or copy_mode:
    generate_map_commands()
else:
    skip_map()

```

**Comment by lucemia** [comment]
Glad to hear your issue is resolved! 🎉

Regarding backwards compatibility — I totally agree that it’s a tricky one. The main challenge is that sometimes the command needs -map, and other times it can rely on FFmpeg’s default behavior, depending on the context. I’m still working through where exactly to draw the line between when it should be added and when it’s safe to omit.

Personally, I lean toward more explicit solutions for clarity, but I’ve also started identifying some patterns and potential rules that could help automate this more intuitively. It’s definitely something I’ll keep in mind for a future update.

Thanks again for the thoughtful feedback! 🙏

**Comment by lucemia** [comment]
@mateusz-krainski-revoize 

Thanks again, just wanted to let you know that the auto -map omission feature has finally been added and released! [3.1.1](https://github.com/livingbio/typed-ffmpeg/releases/tag/3.1.1)

Appreciate your detailed feedback and suggestions on improving intuitive usage and backward compatibility — totally makes sense. Let me know if you run into anything else!

https://github.com/livingbio/typed-ffmpeg/pull/588
